### ISSUE TITLE
Wait for Drupal 7 Commons release, or use 6.22?

### ISSUE THREAD

**Issue by Waitak** [acquia/commons#32]
I'm brand new to Drupal, and looking to convert a Radiant site. Commons looks like the logical installation profile for the site (www.WildcatCenter.org). I note that the current distribution requires Drupal 6.22. If a distribution based on Drupal 7 is forthcoming, I'd rather not have to upgrade just after starting out. Should I wait, or should I plunge in with the current distribution? (I'm posting this here in response to "please use the issue queue for the relevant project" on ezra-g's drupal.org profile.)

**Comment by ezra-g** [comment]
I suggest using the current version of Commons rather than waiting for a 7.x version. Thanks for trying to follow the instructions, the correct place to post is actually the _Drupal.org_ Issue queue: http://drupal.org/project/issues/commons :).

**Comment by Waitak** [comment]
Ah, that'd make sense. As I said, I'm new to Drupal... Thanks for the quick response.

**Comment by ezra-g** [comment]
Welcome!
